PRODUCT = quality-gate
PREFIX ?= /usr/local/custom
INSTALL_DIR = $(PREFIX)/bin
BUILD_DIR_RELEASE = .build/release
BUILD_DIR_DEBUG = .build/debug
STAMP_FILE = $(INSTALL_DIR)/.quality-gate-stamp
BUILD_STAMP_SWIFT = Sources/QualityGateCLI/BuildStamp.swift

.PHONY: build install uninstall clean sign-debug stamp

stamp:
	@echo '// Auto-generated by Makefile — do not edit' > $(BUILD_STAMP_SWIFT)
	@echo 'enum BuildStamp {' >> $(BUILD_STAMP_SWIFT)
	@echo '    static let gitCommit = "$(shell git rev-parse HEAD)"' >> $(BUILD_STAMP_SWIFT)
	@echo '    static let buildDate = "$(shell date -u +%Y-%m-%dT%H:%M:%SZ)"' >> $(BUILD_STAMP_SWIFT)
	@echo '}' >> $(BUILD_STAMP_SWIFT)

build: stamp
	swift build -c release --product $(PRODUCT)
	codesign -s - --force --options runtime $(BUILD_DIR_RELEASE)/$(PRODUCT)

sign-debug:
	codesign -s - --force --options runtime $(BUILD_DIR_DEBUG)/$(PRODUCT)

install: build
	sudo install -d $(INSTALL_DIR)
	sudo install -m 755 $(BUILD_DIR_RELEASE)/$(PRODUCT) $(INSTALL_DIR)/$(PRODUCT)
	sudo xattr -cr $(INSTALL_DIR)/$(PRODUCT)
	@echo "$(shell git rev-parse HEAD)" | sudo tee $(STAMP_FILE) > /dev/null

uninstall:
	sudo rm -f $(INSTALL_DIR)/$(PRODUCT)
	sudo rm -f $(STAMP_FILE)

clean:
	swift package clean
