PRODUCT = quality-gate
PREFIX ?= /usr/local/custom
INSTALL_DIR = $(PREFIX)/bin
BUILD_DIR_RELEASE = .build/release
BUILD_DIR_DEBUG = .build/debug
STAMP_FILE = $(INSTALL_DIR)/.quality-gate-stamp
BUNDLE_NAME = quality-gate-swift_ControlMapping.bundle
BUILD_STAMP_SWIFT = Sources/QualityGateCLI/BuildStamp.swift

.PHONY: build install uninstall clean sign-debug stamp

stamp:
	@echo '// Auto-generated by Makefile — do not edit' > $(BUILD_STAMP_SWIFT)
	@echo 'enum BuildStamp {' >> $(BUILD_STAMP_SWIFT)
	@echo '    static let gitCommit = "$(shell git rev-parse HEAD)"' >> $(BUILD_STAMP_SWIFT)
	@echo '    static let buildDate = "$(shell date -u +%Y-%m-%dT%H:%M:%SZ)"' >> $(BUILD_STAMP_SWIFT)
	@echo '}' >> $(BUILD_STAMP_SWIFT)

# Restores the placeholder after building, so a developer build never leaves a real hash in
# the working tree. `deploy-local.sh` has done this since it was written; this target did not,
# which is how `ad84a35` reached a commit.
restore-stamp:
	@git checkout -- $(BUILD_STAMP_SWIFT) 2>/dev/null || true

build: stamp
	@swift build -c release --product $(PRODUCT); status=$$?; \
	  $(MAKE) --no-print-directory restore-stamp; \
	  test $$status -eq 0
	codesign -s - --force --options runtime $(BUILD_DIR_RELEASE)/$(PRODUCT)

sign-debug:
	codesign -s - --force --options runtime $(BUILD_DIR_DEBUG)/$(PRODUCT)

# SwiftPM resolves resource bundles relative to the executable, so any target with
# resources (ControlMapping ships the regulatory catalogs) needs its .bundle installed
# beside the binary. Installing the binary alone leaves the tool crashing on first use
# of that target — "unable to find bundle named quality-gate-swift_ControlMapping".
install: build
	sudo install -d $(INSTALL_DIR)
	sudo install -m 755 $(BUILD_DIR_RELEASE)/$(PRODUCT) $(INSTALL_DIR)/$(PRODUCT)
	sudo rm -rf $(INSTALL_DIR)/$(BUNDLE_NAME)
	sudo cp -R $(BUILD_DIR_RELEASE)/$(BUNDLE_NAME) $(INSTALL_DIR)/$(BUNDLE_NAME)
	sudo xattr -cr $(INSTALL_DIR)/$(PRODUCT)
	@echo "$(shell git rev-parse HEAD)" | sudo tee $(STAMP_FILE) > /dev/null

uninstall:
	sudo rm -f $(INSTALL_DIR)/$(PRODUCT)
	sudo rm -rf $(INSTALL_DIR)/$(BUNDLE_NAME)
	sudo rm -f $(STAMP_FILE)

clean:
	swift package clean
