import Foundation
import IJSDashboardCore
import IJSSensor

/// Generates a self-contained HTML report from portfolio and pulse data.
///
/// The report uses a CSS Grid layout with stats cards, a two-column main area
/// (project table + pulse summary), a full-width narrative section, and a
/// collapsible sunset section. All CSS and JavaScript are inlined.
public enum HTMLReportRenderer: Sendable {

    /// Produces a complete HTML document as a string.
    ///
    /// - Parameters:
    ///   - portfolio: Aggregated portfolio statistics.
    ///   - projects: Per-project summaries, rendered as a table.
    ///   - pulse: Optional institutional pulse data for the current week.
    /// - Returns: A self-contained HTML string with embedded CSS and JS.
    public static func render(
        portfolio: PortfolioSummary,
        projects: [ProjectSummary],
        pulse: InstitutionalPulse?
    ) -> String {
        render(
            portfolio: portfolio,
            projects: projects,
            pulse: pulse,
            sunsetProjectIDs: []
        )
    }

    /// Produces a complete HTML document, partitioning projects into active and sunset groups.
    ///
    /// Active projects appear in the main sortable table. Sunset projects are placed
    /// in a collapsible `<details>` section at the bottom, collapsed by default.
    ///
    /// - Parameters:
    ///   - portfolio: Aggregated portfolio statistics.
    ///   - projects: Per-project summaries (both active and sunset).
    ///   - pulse: Optional institutional pulse data for the current week.
    ///   - sunsetProjectIDs: Project IDs to treat as sunset/hidden.
    /// - Returns: A self-contained HTML string with embedded CSS and JS.
    public static func render(
        portfolio: PortfolioSummary,
        projects: [ProjectSummary],
        pulse: InstitutionalPulse?,
        sunsetProjectIDs: [String]
    ) -> String {
        let sunsetSet = Set(sunsetProjectIDs)
        let activeProjects = projects.filter { !sunsetSet.contains($0.projectID) }
        let sunsetProjects = projects.filter { sunsetSet.contains($0.projectID) }

        let activePassing = activeProjects.filter(\.latestPassed).count
        let activeFailing = activeProjects.count - activePassing
        let consistencyValue = pulse?.statistics.meanConsistencyScore

        var html = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>IJS Portfolio Report</title>
        <style>
        \(css)
        </style>
        </head>
        <body>
        <div class="container">
        """

        html += renderHeader(portfolio, pulse: pulse)
        html += renderStatsCards(
            activePassing: activePassing,
            activeFailing: activeFailing,
            sunsetCount: sunsetProjects.count,
            consistency: consistencyValue
        )
        html += "<div class=\"dashboard-grid\">"
        html += renderActiveProjectTable(activeProjects)
        html += renderPulseSidebar(pulse, worstCheckers: portfolio.worstCheckers)
        html += "</div>"

        if let pulse {
            html += renderStratificationSection(pulse.projectTiers)
            html += renderTrajectorySection(pulse.projectTrajectories)
            html += renderGroupSection(pulse.groupSnapshots)
        }

        if let pulse, let narrative = pulse.narrative, !narrative.isEmpty {
            html += renderNarrativeSection(narrative)
        }

        html += renderSunsetSection(sunsetProjects)

        html += """
        <footer>
        <p>Generated by IJS Quality Gate</p>
        </footer>
        </div>
        <script>
        \(sortScript)
        </script>
        </body>
        </html>
        """

        return html
    }

    // MARK: - Sections

    private static func renderHeader(
        _ portfolio: PortfolioSummary,
        pulse: InstitutionalPulse?
    ) -> String {
        let weekLabel = pulse.map { escapeHTML($0.label ?? $0.weekLabel) } ?? ""
        let weekSuffix = weekLabel.isEmpty ? "" : "<span class=\"week-label\">\(weekLabel)</span>"
        return """
        <header>
        <div class="header-row">
        <h1>IJS Portfolio Report</h1>
        \(weekSuffix)
        </div>
        </header>
        """
    }

    private static func renderStatsCards(
        activePassing: Int,
        activeFailing: Int,
        sunsetCount: Int,
        consistency: Double?
    ) -> String {
        let consistencyStr: String
        if let c = consistency {
            consistencyStr = c.formatted(.number.precision(.fractionLength(2)))
        } else {
            consistencyStr = "—"
        }
        return """
        <div class="stats-cards">
        <div class="stat-card passing">
        <span class="stat-value">\(activePassing)</span>
        <span class="stat-label">active passing</span>
        </div>
        <div class="stat-card failing">
        <span class="stat-value">\(activeFailing)</span>
        <span class="stat-label">active failing</span>
        </div>
        <div class="stat-card sunset">
        <span class="stat-value">\(sunsetCount)</span>
        <span class="stat-label">sunset</span>
        </div>
        <div class="stat-card consistency">
        <span class="stat-value">\(consistencyStr)</span>
        <span class="stat-label">consistency</span>
        </div>
        </div>
        """
    }

    private static func renderActiveProjectTable(_ projects: [ProjectSummary]) -> String {
        guard !projects.isEmpty else {
            return """
            <section class="projects">
            <h2>Active Projects</h2>
            <p class="empty-state">No active projects.</p>
            </section>
            """
        }

        let sorted = projects.sorted { $0.passRate > $1.passRate }
        var rows = ""
        for project in sorted {
            let status = project.latestPassed ? "&#x2713;" : "&#x2717;"
            let statusClass = project.latestPassed ? "pass" : "fail"
            let pct = Int((project.passRate * 100).rounded())
            rows += """
            <tr>
            <td>\(escapeHTML(project.projectID))</td>
            <td class="\(statusClass)">\(status)</td>
            <td data-sort-value="\(pct)">\(pct)%</td>
            <td data-sort-value="\(project.runCount)">\(project.runCount)</td>
            <td data-sort-value="\(project.totalOverrides)">\(project.totalOverrides)</td>
            </tr>
            """
        }

        return """
        <section class="projects">
        <h2>Active Projects</h2>
        <table id="active-projects-table" class="sortable">
        <thead>
        <tr>\
        <th data-sort="string">Project</th>\
        <th data-sort="status">Status</th>\
        <th data-sort="number">Pass Rate</th>\
        <th data-sort="number">Runs</th>\
        <th data-sort="number">Overrides</th>\
        </tr>
        </thead>
        <tbody>
        \(rows)
        </tbody>
        </table>
        </section>
        """
    }

    private static func renderPulseSidebar(
        _ pulse: InstitutionalPulse?,
        worstCheckers: [String]
    ) -> String {
        guard let pulse else {
            if !worstCheckers.isEmpty {
                return """
                <aside class="pulse-sidebar">
                \(renderWorstCheckers(worstCheckers))
                </aside>
                """
            }
            return "<aside class=\"pulse-sidebar\"></aside>"
        }

        let displayLabel = pulse.label ?? pulse.weekLabel
        var section = """
        <aside class="pulse-sidebar">
        <h2>Pulse \(escapeHTML(displayLabel))</h2>
        """

        section += renderPulseStatistics(pulse.statistics)
        section += renderPulseClusters(pulse.violationClusters)
        section += renderPulseAnomalies(pulse.statistics.anomalies)
        section += renderWorstCheckers(worstCheckers)

        section += "</aside>"
        return section
    }

    private static func renderPulseStatistics(_ stats: PulseStatistics) -> String {
        let passRateStr = stats.passRate.formatted(.number.precision(.fractionLength(1)))
        var html = """
        <div class="pulse-stats">
        <div class="stat-row">
        <span class="stat">Gate Runs: \(stats.totalGateRuns)</span>
        </div>
        <div class="stat-row">
        <span class="stat">Pass Rate: \(passRateStr)%</span>
        <div class="bar-container"><div class="bar-fill" style="width: \(passRateStr)%"></div></div>
        </div>
        <div class="stat-row">
        <span class="stat">Overrides: \(stats.totalOverrides)</span>
        </div>
        <div class="stat-row">
        <span class="stat">Calibrations: \(stats.totalCalibrations)</span>
        </div>
        """

        if let score = stats.meanConsistencyScore {
            let scoreStr = score.formatted(.number.precision(.fractionLength(2)))
            html += """
            <div class="stat-row">
            <span class="stat">Consistency: \(scoreStr)</span>
            </div>
            """
        }

        html += "</div>"
        return html
    }

    private static func renderPulseClusters(_ clusters: [ViolationCluster]) -> String {
        let top = Array(clusters.prefix(5))
        guard !top.isEmpty else { return "" }

        var rows = ""
        for cluster in top {
            let recurring = cluster.isRecurring
                ? " <span class=\"recurring\">RECURRING</span>"
                : ""
            rows += """
            <tr>
            <td>\(escapeHTML(cluster.ruleId))</td>
            <td>\(cluster.occurrenceCount)</td>
            <td>\(cluster.affectedProjectCount)</td>
            <td>\(recurring)</td>
            </tr>
            """
        }

        return """
        <div class="clusters">
        <h3>Top Violations</h3>
        <table>
        <thead>
        <tr><th>Rule</th><th>Occurrences</th><th>Projects</th><th></th></tr>
        </thead>
        <tbody>
        \(rows)
        </tbody>
        </table>
        </div>
        """
    }

    private static func renderPulseAnomalies(_ anomalies: [StatisticalAnomaly]) -> String {
        guard !anomalies.isEmpty else { return "" }

        var items = ""
        for anomaly in anomalies {
            let direction = anomaly.direction == .negative ? "&#x2193;" : "&#x2191;"
            let zStr = abs(anomaly.zScore).formatted(.number.precision(.fractionLength(2)))
            items += """
            <li class="anomaly \(anomaly.severity.rawValue)">
            \(escapeHTML(anomaly.metric)): z=\(zStr)
            (\(anomaly.severity.rawValue), \(direction))
            </li>
            """
        }

        return """
        <div class="anomalies">
        <h3>Anomalies</h3>
        <ul>
        \(items)
        </ul>
        </div>
        """
    }

    private static func renderWorstCheckers(_ checkers: [String]) -> String {
        guard !checkers.isEmpty else { return "" }

        let items = checkers.prefix(5).map { "<li>\(escapeHTML($0))</li>" }.joined(separator: "\n")
        return """
        <div class="worst-checkers">
        <h3>Worst Checkers</h3>
        <ul>
        \(items)
        </ul>
        </div>
        """
    }

    private static func renderNarrativeSection(_ narrative: String) -> String {
        """
        <section class="narrative">
        <h2>Narrative</h2>
        <p>\(escapeHTML(narrative))</p>
        </section>
        """
    }

    private static func renderSunsetSection(_ projects: [ProjectSummary]) -> String {
        guard !projects.isEmpty else { return "" }

        let sorted = projects.sorted { $0.passRate > $1.passRate }
        var rows = ""
        for project in sorted {
            let status = project.latestPassed ? "&#x2713;" : "&#x2717;"
            let statusClass = project.latestPassed ? "pass" : "fail"
            let pct = Int((project.passRate * 100).rounded())
            rows += """
            <tr>
            <td>\(escapeHTML(project.projectID))</td>
            <td class="\(statusClass)">\(status)</td>
            <td>\(pct)%</td>
            <td>\(project.runCount)</td>
            </tr>
            """
        }

        return """
        <details class="sunset-section">
        <summary>Sunset Projects (\(projects.count))</summary>
        <table>
        <thead>
        <tr><th>Project</th><th>Status</th><th>Pass Rate</th><th>Runs</th></tr>
        </thead>
        <tbody>
        \(rows)
        </tbody>
        </table>
        </details>
        """
    }

    private static func renderStratificationSection(
        _ tiers: [String: ProjectTier]?
    ) -> String {
        guard let tiers, !tiers.isEmpty else { return "" }

        var counts: [ProjectTier: Int] = [:]
        for tier in tiers.values {
            counts[tier, default: 0] += 1
        }

        let ordered: [ProjectTier] = [.active, .baseline, .firstContact, .atRisk, .dormant]
        let tierColors: [ProjectTier: String] = [
            .active: "var(--green)",
            .baseline: "var(--cyan)",
            .firstContact: "var(--yellow)",
            .atRisk: "var(--red)",
            .dormant: "var(--text-dim)",
        ]

        var cards = ""
        for tier in ordered {
            guard let count = counts[tier], count > 0 else { continue }
            let color = tierColors[tier] ?? "var(--text)"
            cards += """
            <div class="tier-card" style="border-left: 3px solid \(color);">
            <span class="tier-count" style="color: \(color);">\(count)</span>
            <span class="tier-name">\(tier.rawValue)</span>
            </div>
            """
        }

        return """
        <section class="stratification">
        <h2>Project Tiers</h2>
        <div class="tier-cards">
        \(cards)
        </div>
        </section>
        """
    }

    private static func renderTrajectorySection(
        _ trajectories: [ProjectTrajectory]?
    ) -> String {
        guard let trajectories, !trajectories.isEmpty else { return "" }

        var directionCounts: [TrajectoryDirection: Int] = [:]
        for traj in trajectories {
            directionCounts[traj.direction, default: 0] += 1
        }

        let arrows: [TrajectoryDirection: String] = [
            .improving: "&#x2191;",
            .stable: "&#x2192;",
            .declining: "&#x2193;",
            .insufficient: "?",
        ]
        let colors: [TrajectoryDirection: String] = [
            .improving: "var(--green)",
            .stable: "var(--cyan)",
            .declining: "var(--red)",
            .insufficient: "var(--text-dim)",
        ]
        let directionOrder: [TrajectoryDirection] = [.improving, .stable, .declining, .insufficient]

        var summaryItems = ""
        for dir in directionOrder {
            guard let count = directionCounts[dir], count > 0 else { continue }
            let arrow = arrows[dir] ?? ""
            let color = colors[dir] ?? "var(--text)"
            summaryItems += "<span style=\"color: \(color);\">\(arrow) \(count) \(dir.rawValue)</span> "
        }

        var topMovers = ""
        let validTrajectories = trajectories
            .filter { $0.direction != .insufficient }
            .sorted { abs($0.slope) > abs($1.slope) }
        let top = Array(validTrajectories.prefix(5))
        if !top.isEmpty {
            var rows = ""
            for traj in top {
                let arrow = traj.slope >= 0 ? "&#x2191;" : "&#x2193;"
                let color = traj.slope >= 0 ? "var(--green)" : "var(--red)"
                let slopeStr = abs(traj.slope).formatted(.number.precision(.fractionLength(3)))
                rows += """
                <tr>
                <td>\(escapeHTML(traj.projectID))</td>
                <td style="color: \(color);">\(arrow) \(slopeStr)</td>
                <td>\(traj.direction.rawValue)</td>
                </tr>
                """
            }
            topMovers = """
            <h3>Top Movers</h3>
            <table>
            <thead><tr><th>Project</th><th>Slope</th><th>Direction</th></tr></thead>
            <tbody>\(rows)</tbody>
            </table>
            """
        }

        return """
        <section class="trajectories">
        <h2>Trajectories</h2>
        <div class="trajectory-summary">\(summaryItems)</div>
        \(topMovers)
        </section>
        """
    }

    private static func renderGroupSection(
        _ groupSnapshots: [String: [DailySnapshot]]?
    ) -> String {
        guard let groupSnapshots, !groupSnapshots.isEmpty else { return "" }

        var rows = ""
        let sortedGroups = groupSnapshots.keys.sorted()
        for group in sortedGroups {
            guard let snapshots = groupSnapshots[group], !snapshots.isEmpty else { continue }
            guard let latest = snapshots.sorted(by: { $0.date < $1.date }).last else { continue }
            let pct = Int((latest.passRate * 100).rounded())
            let color = pct >= 70 ? "var(--green)" : (pct >= 50 ? "var(--yellow)" : "var(--red)")
            rows += """
            <tr>
            <td>\(escapeHTML(group))</td>
            <td style="color: \(color);">\(pct)%</td>
            <td>\(latest.gateRuns)</td>
            </tr>
            """
        }

        return """
        <section class="group-summary">
        <h2>Groups</h2>
        <table>
        <thead><tr><th>Group</th><th>Pass Rate</th><th>Runs</th></tr></thead>
        <tbody>\(rows)</tbody>
        </table>
        </section>
        """
    }

    // MARK: - Utilities

    private static func escapeHTML(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    // MARK: - JavaScript

    private static let sortScript = """
    (function() {
      document.querySelectorAll('table.sortable').forEach(function(table) {
        var headers = table.querySelectorAll('thead th');
        var currentCol = -1, ascending = true;
        headers.forEach(function(th, colIdx) {
          th.style.cursor = 'pointer';
          th.addEventListener('click', function() {
            if (currentCol === colIdx) { ascending = !ascending; }
            else { currentCol = colIdx; ascending = true; }
            headers.forEach(function(h) { h.classList.remove('sort-asc', 'sort-desc'); });
            th.classList.add(ascending ? 'sort-asc' : 'sort-desc');
            var tbody = table.querySelector('tbody');
            var rows = Array.from(tbody.querySelectorAll('tr'));
            var sortType = th.getAttribute('data-sort') || 'string';
            rows.sort(function(a, b) {
              var cellA = a.children[colIdx], cellB = b.children[colIdx];
              var valA, valB;
              if (sortType === 'number') {
                valA = parseFloat(cellA.getAttribute('data-sort-value') || cellA.textContent) || 0;
                valB = parseFloat(cellB.getAttribute('data-sort-value') || cellB.textContent) || 0;
              } else if (sortType === 'status') {
                valA = cellA.textContent.trim() === '\\u2713' ? 0 : 1;
                valB = cellB.textContent.trim() === '\\u2713' ? 0 : 1;
              } else {
                valA = cellA.textContent.trim().toLowerCase();
                valB = cellB.textContent.trim().toLowerCase();
              }
              var cmp = valA < valB ? -1 : valA > valB ? 1 : 0;
              return ascending ? cmp : -cmp;
            });
            rows.forEach(function(row) { tbody.appendChild(row); });
          });
        });
      });
    })();
    """

    // MARK: - CSS

    private static let css = """
    :root {
      --bg: #1a1a2e;
      --surface: #16213e;
      --surface-alt: #1a2744;
      --border: #0f3460;
      --text: #e0e0e0;
      --text-dim: #888;
      --green: #4caf50;
      --red: #f44336;
      --yellow: #ffc107;
      --cyan: #00bcd4;
      --card-bg: #16213e;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
    }
    .container {
      max-width: 1100px;
      margin: 0 auto;
      padding: 2rem 1rem;
    }
    header { margin-bottom: 1.5rem; }
    .header-row {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      flex-wrap: wrap;
      gap: 1rem;
    }
    h1 { font-size: 1.8rem; }
    .week-label { font-size: 1rem; color: var(--text-dim); }
    h2 { font-size: 1.3rem; margin: 0 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.25rem; }
    h3 { font-size: 1.1rem; margin: 1rem 0 0.5rem; }

    /* Stats Cards */
    .stats-cards {
      display: flex;
      gap: 1rem;
      flex-wrap: wrap;
      margin-bottom: 1.5rem;
    }
    .stat-card {
      flex: 1;
      min-width: 120px;
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1rem;
      text-align: center;
    }
    .stat-card .stat-value {
      display: block;
      font-size: 1.8rem;
      font-weight: 700;
      line-height: 1.2;
    }
    .stat-card .stat-label {
      display: block;
      font-size: 0.8rem;
      color: var(--text-dim);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .stat-card.passing .stat-value { color: var(--green); }
    .stat-card.failing .stat-value { color: var(--red); }
    .stat-card.sunset .stat-value { color: var(--text-dim); }
    .stat-card.consistency .stat-value { color: var(--cyan); }

    /* Dashboard Grid */
    .dashboard-grid {
      display: grid;
      grid-template-columns: 1fr 320px;
      gap: 1.5rem;
      align-items: start;
    }

    /* Projects Table */
    .projects { min-width: 0; }
    .empty-state { color: var(--text-dim); font-style: italic; }
    table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
    th, td { text-align: left; padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border); }
    th {
      color: var(--text-dim);
      font-weight: 600;
      font-size: 0.85rem;
      text-transform: uppercase;
      user-select: none;
    }
    th[data-sort] { cursor: pointer; }
    th[data-sort]::after { content: ''; margin-left: 0.3em; }
    th.sort-asc::after { content: ' \\25B2'; }
    th.sort-desc::after { content: ' \\25BC'; }
    .pass { color: var(--green); }
    .fail { color: var(--red); }
    .recurring { color: var(--red); font-weight: 700; font-size: 0.8rem; }

    /* Pulse Sidebar */
    .pulse-sidebar {
      background: var(--surface);
      border-radius: 8px;
      padding: 1.25rem;
    }
    .pulse-stats { margin-bottom: 1rem; }
    .stat-row { display: flex; gap: 1rem; margin-bottom: 0.35rem; align-items: center; }
    .stat { font-size: 0.95rem; }
    .bar-container {
      flex: 1;
      height: 8px;
      background: var(--border);
      border-radius: 4px;
      overflow: hidden;
    }
    .bar-fill {
      height: 100%;
      background: var(--green);
      border-radius: 4px;
      transition: width 0.3s;
    }

    /* Worst Checkers */
    .worst-checkers { margin-top: 0.75rem; }

    /* Narrative */
    .narrative {
      margin-top: 1.5rem;
      background: var(--surface);
      border-radius: 8px;
      padding: 1.25rem;
    }
    .narrative p { margin-top: 0.5rem; white-space: pre-wrap; }

    /* Sunset Section */
    .sunset-section {
      margin-top: 1.5rem;
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 0.75rem 1rem;
    }
    .sunset-section summary {
      cursor: pointer;
      font-weight: 600;
      color: var(--text-dim);
      list-style: revert;
    }
    .sunset-section table { margin-top: 0.75rem; }

    /* Stratification */
    .stratification {
      margin-top: 1.5rem;
      background: var(--surface);
      border-radius: 8px;
      padding: 1.25rem;
    }
    .tier-cards {
      display: flex;
      gap: 0.75rem;
      flex-wrap: wrap;
    }
    .tier-card {
      padding: 0.5rem 1rem;
      background: var(--surface-alt);
      border-radius: 6px;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .tier-count { font-size: 1.3rem; font-weight: 700; }
    .tier-name { font-size: 0.85rem; color: var(--text-dim); text-transform: uppercase; }

    /* Trajectories */
    .trajectories {
      margin-top: 1.5rem;
      background: var(--surface);
      border-radius: 8px;
      padding: 1.25rem;
    }
    .trajectory-summary {
      display: flex;
      gap: 1.5rem;
      flex-wrap: wrap;
      margin-bottom: 0.75rem;
      font-size: 1rem;
      font-weight: 600;
    }

    /* Groups */
    .group-summary {
      margin-top: 1.5rem;
      background: var(--surface);
      border-radius: 8px;
      padding: 1.25rem;
    }

    /* Clusters */
    .clusters table { font-size: 0.9rem; }

    /* Anomalies */
    .anomaly { margin-bottom: 0.25rem; }
    .anomaly.extreme { color: var(--red); }
    .anomaly.significant { color: var(--yellow); }
    .anomaly.notable { color: var(--cyan); }

    /* Lists */
    ul { list-style: none; padding-left: 1rem; }
    li::before { content: "\\2022 "; color: var(--text-dim); }

    /* Footer */
    footer { margin-top: 2rem; text-align: center; color: var(--text-dim); font-size: 0.85rem; }

    /* Responsive */
    @media (max-width: 768px) {
      .dashboard-grid { grid-template-columns: 1fr; }
      .stats-cards { flex-direction: column; }
      .stat-card { min-width: unset; }
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #fafafa;
        --surface: #fff;
        --surface-alt: #f5f5f5;
        --border: #e0e0e0;
        --text: #212121;
        --text-dim: #757575;
        --card-bg: #fff;
      }
    }
    """
}
