import Foundation
import IJSDashboardCore
import IJSSensor

/// Generates a self-contained HTML report from portfolio and pulse data.
public enum HTMLReportRenderer: Sendable {

    /// Produces a complete HTML document as a string.
    ///
    /// - Parameters:
    ///   - portfolio: Aggregated portfolio statistics.
    ///   - projects: Per-project summaries, rendered as a table.
    ///   - pulse: Optional institutional pulse data for the current week.
    /// - Returns: A self-contained HTML string with embedded CSS.
    public static func render(
        portfolio: PortfolioSummary,
        projects: [ProjectSummary],
        pulse: InstitutionalPulse?
    ) -> String {
        var html = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>IJS Portfolio Report</title>
        <style>
        \(css)
        </style>
        </head>
        <body>
        <div class="container">
        """

        html += renderPortfolioHeader(portfolio)
        html += renderProjectTable(projects)
        html += renderWorstCheckers(portfolio.worstCheckers)

        if let pulse {
            html += renderPulseSection(pulse)
        }

        html += """
        <footer>
        <p>Generated by IJS Quality Gate</p>
        </footer>
        </div>
        </body>
        </html>
        """

        return html
    }

    // MARK: - Sections

    private static func renderPortfolioHeader(_ portfolio: PortfolioSummary) -> String {
        """
        <header>
        <h1>IJS Portfolio Report</h1>
        <div class="summary-bar">
        <span class="stat">\(portfolio.totalProjects) projects</span>
        <span class="stat passing">\(portfolio.passingProjects) passing</span>
        <span class="stat failing">\(portfolio.failingProjects) failing</span>
        </div>
        </header>
        """
    }

    private static func renderProjectTable(_ projects: [ProjectSummary]) -> String {
        guard !projects.isEmpty else { return "" }

        let sorted = projects.sorted { $0.passRate > $1.passRate }
        var rows = ""
        for project in sorted {
            let status = project.latestPassed ? "&#x2713;" : "&#x2717;"
            let statusClass = project.latestPassed ? "pass" : "fail"
            let pct = Int((project.passRate * 100).rounded())
            rows += """
            <tr>
            <td>\(escapeHTML(project.projectID))</td>
            <td class="\(statusClass)">\(status)</td>
            <td>\(pct)%</td>
            <td>\(project.runCount)</td>
            <td>\(project.totalOverrides)</td>
            </tr>
            """
        }

        return """
        <section class="projects">
        <h2>Projects</h2>
        <table>
        <thead>
        <tr><th>Project</th><th>Status</th><th>Pass Rate</th><th>Runs</th><th>Overrides</th></tr>
        </thead>
        <tbody>
        \(rows)
        </tbody>
        </table>
        </section>
        """
    }

    private static func renderWorstCheckers(_ checkers: [String]) -> String {
        guard !checkers.isEmpty else { return "" }

        let items = checkers.prefix(5).map { "<li>\(escapeHTML($0))</li>" }.joined(separator: "\n")
        return """
        <section class="worst-checkers">
        <h2>Worst Checkers</h2>
        <ul>
        \(items)
        </ul>
        </section>
        """
    }

    private static func renderPulseSection(_ pulse: InstitutionalPulse) -> String {
        var section = """
        <section class="pulse">
        <h2>Pulse \(escapeHTML(pulse.weekLabel))</h2>
        """

        section += renderPulseStatistics(pulse.statistics)
        section += renderPulseClusters(pulse.violationClusters)
        section += renderPulseAnomalies(pulse.statistics.anomalies)

        if let narrative = pulse.narrative, !narrative.isEmpty {
            section += """
            <div class="narrative">
            <h3>Narrative</h3>
            <p>\(escapeHTML(narrative))</p>
            </div>
            """
        }

        section += "</section>"
        return section
    }

    private static func renderPulseStatistics(_ stats: PulseStatistics) -> String {
        let passRateStr = stats.passRate.formatted(.number.precision(.fractionLength(1)))
        var html = """
        <div class="pulse-stats">
        <div class="stat-row">
        <span class="stat">Gate Runs: \(stats.totalGateRuns)</span>
        <span class="stat">Pass Rate: \(passRateStr)%</span>
        </div>
        <div class="stat-row">
        <span class="stat">Overrides: \(stats.totalOverrides)</span>
        <span class="stat">Calibrations: \(stats.totalCalibrations)</span>
        </div>
        """

        if let score = stats.meanConsistencyScore {
            let scoreStr = score.formatted(.number.precision(.fractionLength(2)))
            html += """
            <div class="stat-row">
            <span class="stat">Consistency: \(scoreStr)</span>
            </div>
            """
        }

        html += "</div>"
        return html
    }

    private static func renderPulseClusters(_ clusters: [ViolationCluster]) -> String {
        let top = Array(clusters.prefix(5))
        guard !top.isEmpty else { return "" }

        var rows = ""
        for cluster in top {
            let recurring = cluster.isRecurring
                ? " <span class=\"recurring\">RECURRING</span>"
                : ""
            rows += """
            <tr>
            <td>\(escapeHTML(cluster.ruleId))</td>
            <td>\(cluster.occurrenceCount)</td>
            <td>\(cluster.affectedProjectCount)</td>
            <td>\(recurring)</td>
            </tr>
            """
        }

        return """
        <div class="clusters">
        <h3>Violation Clusters</h3>
        <table>
        <thead>
        <tr><th>Rule</th><th>Occurrences</th><th>Projects</th><th></th></tr>
        </thead>
        <tbody>
        \(rows)
        </tbody>
        </table>
        </div>
        """
    }

    private static func renderPulseAnomalies(_ anomalies: [StatisticalAnomaly]) -> String {
        guard !anomalies.isEmpty else { return "" }

        var items = ""
        for anomaly in anomalies {
            let direction = anomaly.direction == .negative ? "&#x2193;" : "&#x2191;"
            let zStr = abs(anomaly.zScore).formatted(.number.precision(.fractionLength(2)))
            items += """
            <li class="anomaly \(anomaly.severity.rawValue)">
            \(escapeHTML(anomaly.metric)): z=\(zStr)
            (\(anomaly.severity.rawValue), \(direction))
            </li>
            """
        }

        return """
        <div class="anomalies">
        <h3>Anomalies</h3>
        <ul>
        \(items)
        </ul>
        </div>
        """
    }

    // MARK: - Utilities

    private static func escapeHTML(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    // MARK: - CSS

    private static let css = """
    :root {
      --bg: #1a1a2e;
      --surface: #16213e;
      --border: #0f3460;
      --text: #e0e0e0;
      --text-dim: #888;
      --green: #4caf50;
      --red: #f44336;
      --yellow: #ffc107;
      --cyan: #00bcd4;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
    }
    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 2rem 1rem;
    }
    header { margin-bottom: 2rem; }
    h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { font-size: 1.3rem; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.25rem; }
    h3 { font-size: 1.1rem; margin: 1rem 0 0.5rem; }
    .summary-bar { display: flex; gap: 1.5rem; }
    .stat { font-size: 1rem; }
    .passing { color: var(--green); }
    .failing { color: var(--red); }
    table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
    th, td { text-align: left; padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border); }
    th { color: var(--text-dim); font-weight: 600; font-size: 0.85rem; text-transform: uppercase; }
    .pass { color: var(--green); }
    .fail { color: var(--red); }
    .recurring { color: var(--red); font-weight: 700; font-size: 0.8rem; }
    .pulse { background: var(--surface); border-radius: 8px; padding: 1.25rem; margin-top: 1.5rem; }
    .pulse-stats { margin-bottom: 1rem; }
    .stat-row { display: flex; gap: 2rem; margin-bottom: 0.25rem; }
    .anomaly { margin-bottom: 0.25rem; }
    .anomaly.extreme { color: var(--red); }
    .anomaly.significant { color: var(--yellow); }
    .anomaly.notable { color: var(--cyan); }
    .narrative p { margin-top: 0.5rem; white-space: pre-wrap; }
    ul { list-style: none; padding-left: 1rem; }
    li::before { content: "\\2022 "; color: var(--text-dim); }
    footer { margin-top: 2rem; text-align: center; color: var(--text-dim); font-size: 0.85rem; }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #fafafa;
        --surface: #fff;
        --border: #e0e0e0;
        --text: #212121;
        --text-dim: #757575;
      }
    }
    """
}
