import Foundation

/// The self-contained output of `quality-gate orient` for one package:
/// summary prose, external composition, and the legibility map.
struct OrientDocument: Sendable, Codable, Equatable {
    /// Display name of the analyzed package.
    let packageName: String
    /// "What it does" prose (description comment → Master Plan → README lead).
    let summary: String?
    /// External packages this one is built from.
    let builtFrom: [String]
    /// Reading order, module cards, and cycles.
    let map: LegibilityMap
    /// Whether the output must carry the foreign-provenance watermark.
    let watermarked: Bool
}

/// Renders an ``OrientDocument`` for stdout or file output.
///
/// Roles are labeled *(inferred)* — the tool describes structure, it does not
/// speak for design intent — and foreign output carries the provenance
/// watermark so generated artifacts can never read as the project's own
/// standard (Phase 1 §2b).
enum OrientRenderer {
    /// The §2b provenance watermark for output produced against a repo that
    /// declares no quality-gate configuration of its own.
    static let watermarkText =
        "Generated by quality-gate in foreign mode against the contributor's "
        + "configuration — this does not represent the project's own quality standard."

    /// One-page human-readable Markdown.
    static func markdown(_ document: OrientDocument) -> String {
        var lines: [String] = []
        lines.append("# \(document.packageName)")
        lines.append("")
        if let summary = document.summary {
            lines.append(summary)
            lines.append("")
        }
        if !document.builtFrom.isEmpty {
            lines.append("**Built from:** \(document.builtFrom.joined(separator: ", "))")
            lines.append("")
        }
        lines.append("## Reading Order")
        lines.append("")
        lines.append("Study these modules in order — the most foundational first:")
        lines.append("")
        for (index, module) in document.map.readingOrder.enumerated() {
            lines.append("\(index + 1). \(module)")
        }
        if !document.map.cards.isEmpty {
            lines.append("")
            lines.append("## Module Cards")
            lines.append("")
            lines.append("| Module | Role (inferred) | Relied on by | Depends on | Oriented | Over-public |")
            lines.append("| --- | --- | ---: | ---: | :---: | ---: |")
            for card in document.map.cards {
                let oriented = card.hasOrientationDoc ? "✓" : "—"
                lines.append("| \(card.moduleName) | \(card.role) | \(card.fanIn) | \(card.fanOut) | \(oriented) | \(card.overPublicCount) |")
            }
        }
        if !document.map.cycles.isEmpty {
            lines.append("")
            lines.append("## Dependency Cycles")
            lines.append("")
            lines.append("These modules cannot be read in isolation — break them for a clean order:")
            lines.append("")
            for cycle in document.map.cycles {
                lines.append("- \(cycle.sorted().joined(separator: " → "))")
            }
        }
        if document.watermarked {
            lines.append("")
            lines.append("---")
            lines.append("_\(watermarkText)_")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// Deterministic pretty JSON (sorted keys) of the full document.
    static func json(_ document: OrientDocument) throws -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(document)
        return String(decoding: data, as: UTF8.self)
    }
}
