#!/usr/bin/env bash
# v6 #4: regenerate the auto-generated portion of the well-known
# protocol-witness allow-list from the current Swift toolchain's symbol
# graph. Run after a Swift / Xcode update (especially after WWDC) and
# commit the resulting diff. The CI workflow under .github/workflows/
# runs this weekly and opens a PR if anything changed.
#
# Requirements: Xcode + jq.
# Usage:        scripts/regenerate-witnesses.sh
# Output:       Sources/UnreachableCodeAuditor/WellKnownWitnesses+Generated.swift

set -euo pipefail

cd "$(dirname "$0")/.."

# Modules to extract. Add new ones here when Apple ships a new framework
# whose protocols you want covered.
MODULES=(
    # Swift stdlib top-level. Encodable, Hashable, Equatable,
    # CustomStringConvertible, ExpressibleBy*Literal, Identifiable, …
    Swift
    # Concurrency primitives. Actor, AsyncSequence, AsyncIteratorProtocol,
    # Clock, Executor, GlobalActor, SerialExecutor, TaskExecutor — these
    # used to live under `Swift` directly but now have their canonical
    # definitions inside `_Concurrency` and are re-exported. Without this
    # entry the regen produces a PR that "removes" all of them, which
    # would trigger false positives on every modern async-aware codebase.
    _Concurrency
    # Regex / string processing. RegexComponent, CustomConsumingRegexComponent,
    # RegexBuilder, etc. Same re-export story as _Concurrency.
    _StringProcessing
    Foundation
    SwiftUI
    UIKit
    AppKit
    Combine
    SwiftData
    Observation
    CoreData
    CoreGraphics
    OSLog
    Charts
)

SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="arm64-apple-macos14"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

OUT="Sources/UnreachableCodeAuditor/WellKnownWitnesses+Generated.swift"
TMP="$WORK_DIR/generated.swift"

echo "Extracting symbol graphs into $WORK_DIR..."
for module in "${MODULES[@]}"; do
    mkdir -p "$WORK_DIR/$module"
    if xcrun swift symbolgraph-extract \
            -module-name "$module" \
            -target "$TARGET" \
            -sdk "$SDK_PATH" \
            -output-dir "$WORK_DIR/$module" \
            -minimum-access-level public \
            2>/dev/null; then
        echo "  $module ✓"
    else
        echo "  $module ✗ (skipped — module not available for this SDK)"
    fi
done

# Walk every produced .symbols.json and emit "<module>|<protocol>|<requirement>"
# tuples. The grouping is the qualitative context for PR reviewers — when
# Apple ships a new protocol the diff will show its `// MARK:` section
# arriving with all of its requirements, instead of opaque new names
# scattered alphabetically through a flat list.
echo
echo "Parsing protocol requirements..."
TUPLES_FILE="$WORK_DIR/tuples.txt"
: > "$TUPLES_FILE"

for module in "${MODULES[@]}"; do
    find "$WORK_DIR/$module" -name '*.symbols.json' 2>/dev/null | while IFS= read -r json; do
        jq -r --arg module "$module" '
            # Build a USR -> display-name lookup for every symbol in this file.
            ( .symbols
              | map({ key: .identifier.precise, value: .names.title })
              | from_entries
            ) as $names
            # For each requirement-of relationship, emit a tuple. Filter out
            # entries whose source or target is missing from $names (those
            # come from a different module symbol graph and that module
            # pass will own them).
            | .relationships[]?
            | select(.kind == "requirementOf" or .kind == "optionalRequirementOf")
            | select(($names[.source] // null) != null and ($names[.target] // null) != null)
            | "\($module)|\($names[.target])|\($names[.source])"
        ' "$json" >> "$TUPLES_FILE" 2>/dev/null || true
    done
done

# Stable order: module, then protocol, then requirement name.
SORTED_FILE="$WORK_DIR/sorted.txt"
sort -t'|' -k1,1 -k2,2 -k3,3 -u "$TUPLES_FILE" > "$SORTED_FILE"

UNIQUE_NAMES="$(awk -F'|' '{ print $3 }' "$SORTED_FILE" | sort -u | grep -c . || true)"
PROTOCOL_COUNT="$(awk -F'|' '{ print $1"|"$2 }' "$SORTED_FILE" | sort -u | grep -c . || true)"
echo "  found $UNIQUE_NAMES unique requirement names across $PROTOCOL_COUNT protocols"

DATE="$(date +%Y-%m-%d)"
TOOLCHAIN="$(xcrun swift --version | head -1)"

{
    cat <<HEADER
// DO NOT EDIT — this file is generated by scripts/regenerate-witnesses.sh
// from the current Swift toolchain's symbol graph. Re-run that script
// after a Swift / Xcode update (especially after WWDC) and commit the
// resulting diff. The CI cron job under .github/workflows/ does this
// weekly and opens a PR automatically.
//
// Names are grouped by \`Module.Protocol\` so that when Apple ships a
// new protocol you see its whole \`// MARK:\` section arrive in the diff
// — easy to skim, easy to merge.
//
// Source modules:
//   ${MODULES[*]}
//
// Last regenerated: $DATE
// Toolchain:        $TOOLCHAIN
// Coverage:         $UNIQUE_NAMES requirement names across $PROTOCOL_COUNT protocols

import Foundation

extension WellKnownWitnesses {
    /// Protocol requirement names extracted from Apple framework
    /// symbol graphs. Edit only via the regeneration script.
    ///
    /// Each \`// MARK: - Module.Protocol\` group lists the requirements
    /// of one protocol. The same requirement name can appear under
    /// multiple protocols (e.g. \`description\` shows up in any protocol
    /// that re-states \`CustomStringConvertible\`'s requirement); the
    /// underlying \`Set<String>\` deduplicates them at runtime.
    static let generated: Set<String> = [
HEADER

    awk -F'|' '
        BEGIN { last_group = "" }
        NF == 3 {
            group = $1 "." $2
            if (group != last_group) {
                if (last_group != "") print ""
                printf "        // MARK: - %s\n", group
                last_group = group
            }
            # Escape any literal backslashes or double-quotes in the name.
            name = $3
            gsub(/\\/, "\\\\", name)
            gsub(/"/, "\\\"", name)
            printf "        \"%s\",\n", name
        }
    ' "$SORTED_FILE"

    cat <<'FOOTER'
    ]
}
FOOTER
} > "$TMP"

mv "$TMP" "$OUT"
echo
echo "Wrote $OUT"
git diff --stat "$OUT" 2>/dev/null || true
