#!/usr/bin/env bash
# Produce a human-readable Markdown summary of the diff between two
# generated witness allow-list files. Used by the regenerate-witnesses
# GitHub Actions workflow as the body of the auto-PR — turns "list of
# names" into "Apple added/removed protocols X/Y/Z, here's what each
# means". Run by hand:
#
#   scripts/witness-diff-summary.sh OLD.swift NEW.swift > summary.md
#
# Output is Markdown.

set -euo pipefail

OLD="${1:-}"
NEW="${2:-}"
if [ -z "$OLD" ] || [ -z "$NEW" ]; then
    echo "usage: $0 <old.swift> <new.swift>" >&2
    exit 2
fi

# Extract `(group, name)` pairs from a generated file. Each `// MARK: -
# Module.Protocol` line starts a new group; subsequent `"name"` lines
# belong to that group until the next MARK or `]`. Output is one line
# per (group, name) pair, sorted.
extract() {
    awk '
        /^[[:space:]]*\/\/ MARK: - / {
            sub(/^[[:space:]]*\/\/ MARK: - /, "")
            group = $0
            next
        }
        /^[[:space:]]*"/ && group != "" {
            line = $0
            sub(/^[[:space:]]*"/, "", line)
            sub(/",?[[:space:]]*$/, "", line)
            print group "|" line
        }
    ' "$1" | sort -u
}

OLD_PAIRS="$(mktemp)"
NEW_PAIRS="$(mktemp)"
trap 'rm -f "$OLD_PAIRS" "$NEW_PAIRS"' EXIT

extract "$OLD" > "$OLD_PAIRS"
extract "$NEW" > "$NEW_PAIRS"

# Quick counts.
OLD_GROUPS="$(awk -F'|' '{ print $1 }' "$OLD_PAIRS" | sort -u | grep -c . || true)"
NEW_GROUPS="$(awk -F'|' '{ print $1 }' "$NEW_PAIRS" | sort -u | grep -c . || true)"
OLD_NAMES="$(awk -F'|' '{ print $2 }' "$OLD_PAIRS" | sort -u | grep -c . || true)"
NEW_NAMES="$(awk -F'|' '{ print $2 }' "$NEW_PAIRS" | sort -u | grep -c . || true)"

ADDED_PAIRS="$(comm -13 "$OLD_PAIRS" "$NEW_PAIRS")"
REMOVED_PAIRS="$(comm -23 "$OLD_PAIRS" "$NEW_PAIRS")"

ADDED_GROUPS="$(printf '%s\n' "$ADDED_PAIRS" | awk -F'|' 'NF { print $1 }' | sort -u)"
REMOVED_GROUPS="$(printf '%s\n' "$REMOVED_PAIRS" | awk -F'|' 'NF { print $1 }' | sort -u)"

# A "new" group is one that exists in NEW but not in OLD at all.
NEW_ONLY_GROUPS="$(comm -13 \
    <(awk -F'|' 'NF { print $1 }' "$OLD_PAIRS" | sort -u) \
    <(awk -F'|' 'NF { print $1 }' "$NEW_PAIRS" | sort -u))"
GONE_GROUPS="$(comm -23 \
    <(awk -F'|' 'NF { print $1 }' "$OLD_PAIRS" | sort -u) \
    <(awk -F'|' 'NF { print $1 }' "$NEW_PAIRS" | sort -u))"

ADDED_COUNT="$(printf '%s\n' "$ADDED_PAIRS" | grep -c . || true)"
REMOVED_COUNT="$(printf '%s\n' "$REMOVED_PAIRS" | grep -c . || true)"

cat <<HEADER
## Auto-regenerated witness allow-list

Auto-generated by [scripts/regenerate-witnesses.sh](../blob/main/scripts/regenerate-witnesses.sh)
from the current Swift toolchain's symbol graph (likely after an Xcode
or Swift update).

| | Before | After | Δ |
|---|---:|---:|---:|
| Protocols covered | $OLD_GROUPS | $NEW_GROUPS | $((NEW_GROUPS - OLD_GROUPS)) |
| Unique requirement names | $OLD_NAMES | $NEW_NAMES | $((NEW_NAMES - OLD_NAMES)) |
| Pair additions | | | +$ADDED_COUNT |
| Pair removals | | | -$REMOVED_COUNT |

HEADER

if [ -n "$NEW_ONLY_GROUPS" ]; then
    echo "### 🆕 New protocols"
    echo
    echo "Protocols Apple added in this toolchain release (the auditor will"
    echo "now keep witnesses for these alive):"
    echo
    while IFS= read -r group; do
        [ -z "$group" ] && continue
        echo "- **\`$group\`**"
        printf '%s\n' "$ADDED_PAIRS" \
            | awk -F'|' -v g="$group" '$1 == g { printf "    - `%s`\n", $2 }'
    done <<< "$NEW_ONLY_GROUPS"
    echo
fi

if [ -n "$GONE_GROUPS" ]; then
    echo "### 🗑 Removed protocols"
    echo
    echo "Protocols that vanished from the symbol graph entirely. Most"
    echo "likely renamed or deprecated; sanity-check before merging."
    echo
    while IFS= read -r group; do
        [ -z "$group" ] && continue
        echo "- **\`$group\`**"
    done <<< "$GONE_GROUPS"
    echo
fi

# Pairs added to a protocol that already existed in the old file.
EXTENDED_PAIRS="$(printf '%s\n' "$ADDED_PAIRS" \
    | awk -F'|' -v new_only="$NEW_ONLY_GROUPS" '
        BEGIN {
            n = split(new_only, arr, "\n")
            for (i = 1; i <= n; i++) seen[arr[i]] = 1
        }
        NF && !seen[$1]
    ')"

if [ -n "$EXTENDED_PAIRS" ]; then
    echo "### ➕ Extended protocols"
    echo
    echo "Existing protocols that gained requirements (Apple added a new"
    echo "method/property to a protocol you already conform to):"
    echo
    EXTENDED_GROUPS="$(printf '%s\n' "$EXTENDED_PAIRS" | awk -F'|' '{ print $1 }' | sort -u)"
    while IFS= read -r group; do
        [ -z "$group" ] && continue
        echo "- **\`$group\`**"
        printf '%s\n' "$EXTENDED_PAIRS" \
            | awk -F'|' -v g="$group" '$1 == g { printf "    - `%s`\n", $2 }'
    done <<< "$EXTENDED_GROUPS"
    echo
fi

# Pairs removed from a protocol that still exists.
TRIMMED_PAIRS="$(printf '%s\n' "$REMOVED_PAIRS" \
    | awk -F'|' -v gone="$GONE_GROUPS" '
        BEGIN {
            n = split(gone, arr, "\n")
            for (i = 1; i <= n; i++) seen[arr[i]] = 1
        }
        NF && !seen[$1]
    ')"

if [ -n "$TRIMMED_PAIRS" ]; then
    echo "### ➖ Trimmed protocols"
    echo
    echo "Existing protocols that lost a requirement (Apple removed or"
    echo "renamed a method on a protocol you may still conform to —"
    echo "double-check):"
    echo
    TRIMMED_GROUPS="$(printf '%s\n' "$TRIMMED_PAIRS" | awk -F'|' '{ print $1 }' | sort -u)"
    while IFS= read -r group; do
        [ -z "$group" ] && continue
        echo "- **\`$group\`**"
        printf '%s\n' "$TRIMMED_PAIRS" \
            | awk -F'|' -v g="$group" '$1 == g { printf "    - `%s`\n", $2 }'
    done <<< "$TRIMMED_GROUPS"
    echo
fi

if [ "$ADDED_COUNT" -eq 0 ] && [ "$REMOVED_COUNT" -eq 0 ]; then
    echo "### No qualitative changes"
    echo
    echo "The symbol graph regenerated identically — no protocols added,"
    echo "removed, or modified. (This PR shouldn't normally exist; the"
    echo "workflow only opens one when the file actually changed.)"
    echo
fi

cat <<'FOOTER'
---

### Reviewer checklist

- [ ] Toolchain version in the file header looks reasonable (latest Xcode after WWDC?)
- [ ] New protocols above match what Apple actually shipped (skim the
      release notes / WWDC sessions)
- [ ] Removed protocols are explainable (deprecation, rename, refactor)
- [ ] `swift test --filter UnreachableCodeAuditor` is green in this PR's checks

If anything looks off, close this PR and either fix `scripts/regenerate-witnesses.sh`
or pin the previous file by reverting the change.
FOOTER
