import Foundation
import QualityGateCore

/// A single memory file to be written.
public struct MemoryEntry: Sendable, Equatable {
    /// Filename (e.g., "project_profile.md")
    public let filename: String
    /// Memory name shown in frontmatter
    public let name: String
    /// One-line description for MEMORY.md index
    public let description: String
    /// Memory type: user, feedback, project, reference
    public let type: String
    /// The markdown body content (below frontmatter)
    public let body: String

    /// Creates a new memory entry with the given metadata and body content.
    /// - Parameters:
    ///   - filename: Output filename (e.g., "project_profile.md").
    ///   - name: Display name used in frontmatter and the MEMORY.md index.
    ///   - description: One-line summary for the MEMORY.md index.
    ///   - type: Memory category: user, feedback, project, or reference.
    ///   - body: Markdown body content rendered below frontmatter.
    public init(filename: String, name: String, description: String, type: String, body: String) {
        self.filename = filename
        self.name = name
        self.description = description
        self.type = type
        self.body = body
    }
}

/// Renders memory entries to markdown files and manages the MEMORY.md index.
public enum MemoryWriter {

    /// The frontmatter tag that marks a file as generated by MemoryBuilder.
    public static let generatedTag = "generated-by: memory-builder"

    /// The HTML comment appended to generated index lines.
    static let generatedMarker = "<!-- generated -->"

    /// Renders a MemoryEntry to its full markdown file content (with frontmatter).
    public static func render(_ entry: MemoryEntry) -> String {
        """
        ---
        name: \(entry.name)
        description: \(entry.description)
        type: \(entry.type)
        \(generatedTag)
        ---

        \(entry.body)
        """
    }

    /// The id naming the generated region in `MEMORY.md`.
    public static let regionID = "memory-index"

    /// The delimiter opening the generated region.
    public static var regionOpen: String { "<!-- generated:\(regionID) -->" }

    /// The delimiter closing the generated region.
    public static var regionClose: String { "<!-- /generated:\(regionID) -->" }

    /// Renders a single MEMORY.md index line for an entry.
    ///
    /// No per-line marker: the line's membership is decided by the region it sits in. The
    /// suffix form is kept only as something to *recognise* during migration — see
    /// ``mergeIndex(existing:entries:)``.
    public static func indexLine(for entry: MemoryEntry) -> String {
        "- [\(entry.name)](\(entry.filename)) — \(entry.description)"
    }

    /// The file a `- [Name](file.md) — …` line points at, or `nil` when the line is not one.
    ///
    /// This is an index entry's identity. It is the only part two contradictory lines about
    /// one memory are guaranteed to agree on — the name and the description are exactly what
    /// drifts.
    static func linkTarget(of line: String) -> String? {
        guard let close = line.range(of: "]("),
              let end = line.range(of: ")", range: close.upperBound..<line.endIndex)
        else {
            return nil
        }
        let target = String(line[close.upperBound..<end.lowerBound])
        return target.isEmpty ? nil : target
    }

    /// Returns true if the file content was generated by MemoryBuilder.
    public static func isGenerated(_ content: String) -> Bool {
        content.contains(generatedTag)
    }

    /// Merges generated entries into an existing MEMORY.md index, preserving everything the
    /// author wrote.
    ///
    /// ## Why this is a region and not a marker per line
    ///
    /// The previous form appended `<!-- generated -->` to each generated line and partitioned
    /// on it: tagged lines were replaced, untagged lines preserved as manual. **A line that was
    /// generated and then lost its tag became immortal** — through a hand edit, a merge, or a
    /// generator whose output shape changed — because nothing could tell it apart from a line
    /// a person wrote. The line-suffix form cannot express deletion.
    ///
    /// That was not hypothetical. The live index carried five duplicated pairs: two entries
    /// pointing at one file, one saying 72 targets and one saying 116, both loaded at session
    /// start. The reader was handed the truth and its stale contradiction in the same list, and
    /// the generator was structurally incapable of resolving it.
    ///
    /// A region fixes it by construction: everything between the delimiters is the generator's,
    /// everything outside is the author's, and deletion is just "the new region has fewer
    /// lines".
    ///
    /// ## Migration, which happens once and then never matters again
    ///
    /// An index written by the old form has no region. Two kinds of line are absorbed rather
    /// than preserved:
    ///
    /// - anything still carrying the legacy `<!-- generated -->` suffix, and
    /// - any line pointing at a file this run generates — the immortal duplicates, identified
    ///   by their link target because that is the one thing two contradictory entries about one
    ///   memory still agree on.
    ///
    /// The second rule stays in force afterwards rather than being migration-only: two index
    /// entries for one memory file is the defect, whenever it arrives and whoever wrote it.
    ///
    /// - Parameters:
    ///   - existing: The current `MEMORY.md`, or `""` when there is none.
    ///   - entries: The memories this run generated.
    /// - Returns: The merged index, ending in a newline.
    public static func mergeIndex(existing: String, entries: [MemoryEntry]) -> String {
        let generated = entries.map(indexLine(for:))
        let claimed = Set(entries.map(\.filename))
        let lines = existing.isEmpty ? [] : existing.lines

        let open = lines.firstIndex(of: regionOpen)
        let close = lines.firstIndex(of: regionClose)

        /// Author content: legacy-marked lines and duplicate entries are dropped.
        func preserved(_ range: ArraySlice<String>) -> [String] {
            range.filter { line in
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.isEmpty { return false }
                if trimmed.contains(generatedMarker) { return false }
                if let target = linkTarget(of: line), claimed.contains(target) { return false }
                return true
            }
        }

        var result: [String]
        if let open, let close, open < close {
            // A region already exists, so it is rewritten where the author put it. Moving it
            // to the end would reorder a document somebody arranged.
            result = preserved(lines[lines.startIndex..<open])
                + [regionOpen] + generated + [regionClose]
                + preserved(lines[lines.index(after: close)...])
        } else {
            result = preserved(lines[...]) + [regionOpen] + generated + [regionClose]
        }
        return result.joined(separator: "\n") + "\n"
    }
}
