import Foundation

/// A single memory file to be written.
public struct MemoryEntry: Sendable, Equatable {
    /// Filename (e.g., "project_profile.md")
    public let filename: String
    /// Memory name shown in frontmatter
    public let name: String
    /// One-line description for MEMORY.md index
    public let description: String
    /// Memory type: user, feedback, project, reference
    public let type: String
    /// The markdown body content (below frontmatter)
    public let body: String

    public init(filename: String, name: String, description: String, type: String, body: String) {
        self.filename = filename
        self.name = name
        self.description = description
        self.type = type
        self.body = body
    }
}

/// Renders memory entries to markdown files and manages the MEMORY.md index.
public enum MemoryWriter {

    /// The frontmatter tag that marks a file as generated by MemoryBuilder.
    public static let generatedTag = "generated-by: memory-builder"

    /// The HTML comment appended to generated index lines.
    static let generatedMarker = "<!-- generated -->"

    /// Renders a MemoryEntry to its full markdown file content (with frontmatter).
    public static func render(_ entry: MemoryEntry) -> String {
        """
        ---
        name: \(entry.name)
        description: \(entry.description)
        type: \(entry.type)
        \(generatedTag)
        ---

        \(entry.body)
        """
    }

    /// Renders a single MEMORY.md index line for an entry.
    public static func indexLine(for entry: MemoryEntry) -> String {
        "- [\(entry.name)](\(entry.filename)) — \(entry.description) \(generatedMarker)"
    }

    /// Returns true if the file content was generated by MemoryBuilder.
    public static func isGenerated(_ content: String) -> Bool {
        content.contains(generatedTag)
    }

    /// Merges new generated entries into an existing MEMORY.md index string,
    /// preserving manually-written lines.
    public static func mergeIndex(existing: String, entries: [MemoryEntry]) -> String {
        var manualLines: [String] = []
        var generatedLines: [String] = []

        // Separate existing lines into manual and generated
        for line in existing.components(separatedBy: "\n") {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed.isEmpty { continue }
            if trimmed.contains(generatedMarker) {
                // Will be replaced by new generated lines
                continue
            }
            manualLines.append(line)
        }

        // Build new generated lines from entries
        for entry in entries {
            generatedLines.append(indexLine(for: entry))
        }

        var result = manualLines
        result.append(contentsOf: generatedLines)
        return result.joined(separator: "\n") + "\n"
    }
}
