import Foundation

/// A single memory file to be written.
public struct MemoryEntry: Sendable, Equatable {
    /// Filename (e.g., "project_profile.md")
    public let filename: String
    /// Memory name shown in frontmatter
    public let name: String
    /// One-line description for MEMORY.md index
    public let description: String
    /// Memory type: user, feedback, project, reference
    public let type: String
    /// The markdown body content (below frontmatter)
    public let body: String

    public init(filename: String, name: String, description: String, type: String, body: String) {
        self.filename = filename
        self.name = name
        self.description = description
        self.type = type
        self.body = body
    }
}

/// Renders memory entries to markdown files and manages the MEMORY.md index.
public enum MemoryWriter {

    /// The frontmatter tag that marks a file as generated by MemoryBuilder.
    public static let generatedTag = "generated-by: memory-builder"

    /// Renders a MemoryEntry to its full markdown file content (with frontmatter).
    public static func render(_ entry: MemoryEntry) -> String {
        // TODO: Implement — Phase 2
        ""
    }

    /// Renders a single MEMORY.md index line for an entry.
    public static func indexLine(for entry: MemoryEntry) -> String {
        // TODO: Implement — Phase 2
        ""
    }

    /// Returns true if the file at the given content was generated by MemoryBuilder.
    public static func isGenerated(_ content: String) -> Bool {
        // TODO: Implement — Phase 2
        false
    }

    /// Merges new generated entries into an existing MEMORY.md index string,
    /// preserving manually-written lines.
    public static func mergeIndex(existing: String, entries: [MemoryEntry]) -> String {
        // TODO: Implement — Phase 2
        existing
    }
}
